### ISSUE TITLE
untarring failed due to read-only file permissions in some tarballs

### ISSUE THREAD

**Issue by gdevenyi** [NVIDIA/build-system-archive-import-examples#12]
Using the example call from README, the script fails during copytree because of permissions issues with LICENSE file.

It looks like the first package extracts and has a RO LICENCE file, and then the second extraction/copy fails.

```
Archives:
:: tar: cuda_cccl-linux-x86_64-11.4.122-archive.tar.xz
  -> Extracted: cuda_cccl-linux-x86_64-11.4.122-archive/
:: tar: cuda_cudart-linux-x86_64-11.4.108-archive.tar.xz
  -> Extracted: cuda_cudart-linux-x86_64-11.4.108-archive/
Traceback (most recent call last):
  File "/tmp/build-system-archive-import-examples/./parse_redist.py", line 292, in <module>
    post_action()
  File "/tmp/build-system-archive-import-examples/./parse_redist.py", line 173, in post_action
    flatten_tree(topdir, OUTPUT + "/" + platform, binTag)
  File "/tmp/build-system-archive-import-examples/./parse_redist.py", line 84, in flatten_tree
    shutil.copytree(src, dest, symlinks=1, dirs_exist_ok=1, ignore_dangling_symlinks=1)
  File "/home/gdevenyi/mambaforge/envs/polly/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/gdevenyi/mambaforge/envs/polly/lib/python3.10/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('cuda_cudart-linux-x86_64-11.4.108-archive/LICENSE', 'flat/linux-x86_64/LICENSE', "[Errno 13] Permission denied: 'flat/linux-x86_64/LICENSE'")]
```

**Comment by gdevenyi** [comment]
Similarly fails with the latest version, though much later
```
:: tar: libnvjpeg-linux-x86_64-12.3.0.81-archive.tar.xz
  -> Extracted: libnvjpeg-linux-x86_64-12.3.0.81-archive/
:: tar: nsight_compute-linux-x86_64-2023.3.1.1-archive.tar.xz
  -> Extracted: nsight_compute-linux-x86_64-2023.3.1.1-archive/
:: tar: nsight_systems-linux-x86_64-2023.3.3.42-archive.tar.xz
  -> Extracted: nsight_systems-linux-x86_64-2023.3.3.42-archive/
Traceback (most recent call last):
  File "/tmp/build-system-archive-import-examples/./parse_redist.py", line 292, in <module>
    post_action()
  File "/tmp/build-system-archive-import-examples/./parse_redist.py", line 173, in post_action
    flatten_tree(topdir, OUTPUT + "/" + platform, binTag)
  File "/tmp/build-system-archive-import-examples/./parse_redist.py", line 84, in flatten_tree
    shutil.copytree(src, dest, symlinks=1, dirs_exist_ok=1, ignore_dangling_symlinks=1)
  File "/home/gdevenyi/mambaforge/envs/polly/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/gdevenyi/mambaforge/envs/polly/lib/python3.10/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('nsight_systems-linux-x86_64-2023.3.3.42-archive/LICENSE', 'flat/linux-x86_64/LICENSE', "[Errno 13] Permission denied: 'flat/linux-x86_64/LICENSE'")]
```
